# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to publish to
        required: true
        type: choice
        options:
          - production

jobs:
  publish:
    uses: khaitruong922/pypi-publish-reusable-workflow/.github/workflows/publish.yml@master
    with:
      package_name: package123456
      environment: ${{ github.event.inputs.environment}}
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN}}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN}}
      TEST_PYPI_PUBLISH_URL: ${{ secrets.TEST_PYPI_PUBLISH_URL}}
      TEST_PYPI_INSTALL_URL: ${{ secrets.TEST_PYPI_INSTALL_URL}}
